--- 
javascripts: 
- base: 
    - prototype
    - lowpro
    - effects
    - dragdrop
    - cookie
    - controls
    - concertina
    - list
    - inflector
    - tabricator
    - search     
    - browser_timezone
    - autocomplete
    - application     
- tracker_debug:
    - tracker_debug
- tracker:
    - tracker  
stylesheets: 
- base:
    - reset 
    - grid
    - text    
    - layout
    - nav
    - tabricator
    - calendar
    - autocomplete    
    - application
- ie:
    - reset 
    - grid
    - text    
    - layout  
    - nav
    - tabricator
    - calendar
    - autocomplete    
    - application
    - ie  
- ie6:    
    - reset 
    - grid
    - layout
    - nav
    - tabricator
    - text
    - calendar
    - autocomplete    
    - application     
    - ie6        
